### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by noppon0031** [Radency/flutter_customizable_calendar#48]
<img width="302" alt="Screenshot 2567-11-05 at 15 21 38" src="https://github.com/user-attachments/assets/b5f13efc-aa5c-4d55-9bcd-15983b879c0c">

The example below still shows a list for the 11th, but in the calendar it's already the 12th.

**Comment by nop-gkdev** [comment]
help me please

**Comment by nop-gkdev** [comment]
help me please

**Comment by AndriiVivcharenko** [comment]
Hi @noppon0031! Thank you for opening this issue! I’ll be looking into it and will update you as I make progress

**Comment by noppon0031** [comment]
Thank you for following and correcting. We wait for this fix.

**Comment by noppon0031** [comment]
I still face this problem.

**Comment by AndriiVivcharenko** [comment]
> @AndriiVivcharenko I still face this problem.

@noppon0031 Sorry to hear you’re still facing this issue—maybe I misunderstood the issue. Currently, the `displayedDate` state updates as soon as the next day appears at the bottom of the scrolling view boundaries, which was defined as the expected behavior, and it should now work this way in version 0.3.6.

However, I see there might be different cases where switching between modes is useful. I’ve added a new Enum parameter to let you switch between two modes: updating the date when the widget is at the top of the scroll `EScheduleListViewDisplayedDateEdge.leading` or at the bottom `EScheduleListViewDisplayedDateEdge.trailing` 
to compare these two modes, see the attached videos

https://github.com/user-attachments/assets/3c50e1ab-9c00-48bd-ad2d-e251899a74b4

https://github.com/user-attachments/assets/382dda9a-cbdd-4990-99fb-380237da666d




By default, it’s still set to `EScheduleListViewDisplayedDateEdge.trailing` For testing, try setting it to `EScheduleListViewDisplayedDateEdge.leading`, as shown in the updated example app
https://github.com/Radency/flutter_customizable_calendar/blob/16e15b2a84af24bb076b558ccbd299088930e6d7/example/lib/month_view_with_schedule_list_view/month_view_with_schedule_list_view_page.dart#L475-L478

Please use the version from the `release/0.3.7` branch for local testing:

`pubspec.yaml`
```yaml
flutter_customizable_calendar:
  git:
    url: git@github.com:Radency/flutter_customizable_calendar.git
    ref: release/0.3.7
```

Let me know if this gives you the expected behavior!
Thanks

**Comment by noppon0031** [comment]
@AndriiVivcharenko  Thank you very much. My problem is solved. Awesome. But I have a new question. Can I deploy the app to store now? Or have to wait for you to update to 0.3.7 which is not a branch for local testing

**Comment by AndriiVivcharenko** [comment]
> @AndriiVivcharenko Thank you very much. My problem is solved. Awesome. But I have a new question. Can I deploy the app to store now? Or have to wait for you to update to 0.3.7 which is not a branch for local testing

Great to hear it’s working! You’re good to go with deploying the app now. no more changes will be made to this release. I’ll publish version 0.3.7 to pub.dev later today, and I’ll let you know once it’s live, so you can change it back in your `pubspec.yaml`.

**Comment by AndriiVivcharenko** [comment]
@noppon0031 The new version 0.3.7 is now available on [pub.dev](https://pub.dev/packages/flutter_customizable_calendar/versions/0.3.7)

I’ll go ahead and close this issue, but let me know if you run into anything else! Thanks
